### ISSUE TITLE
mobile issue: scroll to header-climb-name needs some offset or padding

### ISSUE THREAD

**Issue by gardaholm** [lemeryfertitta/Climbdex#17]

**Comment by gardaholm** [comment]
on mobile devices: when you click on a climb name and the page scrolls down to div with id=header-climb-name
then the name stays at the top of the screen. would be great to add some padding-top or use a scroll offset. 

Looks a bit tricky on a smartphone because the name stays straight below the browser-bar.

**Comment by lemeryfertitta** [comment]
Thanks for the report! This was actually a really easy fix. We can just scroll the whole div into view instead of the climb header, which gives us the natural padding that already exists between the top of the div and the climb name.

I've deployed the change. I'll close this one out, as I assume this fixes the issue you were experiencing, but feel free to reopen if not.
