### ISSUE TITLE
No matching indicator

### ISSUE THREAD

**Issue by gardaholm** [lemeryfertitta/Climbdex#31]
Not sure if this was already displayed or not. 
Tension uses a separate icon to indicate that a climb is without matching holds. See Screenshot of the app.

I think they have some regex filter on the route description and search for keywords like "no matching / don't match" and then they add this icon next to the route name. There is no toogle to add this when adding a new route.

since most of the harder routes are without matching, this indicator would be helpful.

![signal-2024-02-03-132859_002](https://github.com/lemeryfertitta/Climbdex/assets/7480162/1b94376a-050d-45a5-a2f9-3c0eabcb6f1f)

**Comment by lemeryfertitta** [comment]
On a related note, the description is already made available to the UI here: https://github.com/lemeryfertitta/Climbdex/blob/main/climbdex/static/js/results.js#L98

I had originally been displaying the description in the climb details (i.e. near the setter name and difficulty text above the hold circles), but I didn't settle on a great UI for it. Maybe an alternative here would just be to show the description in a clean way.

**Comment by gardaholm** [comment]
tried a few methods, but a clean description below the climb-svg is probably the best solution, sometimes there are more comments than just a simple "match" or "don't match" information. I used an Icon + Regex before but thats probably too less information. 
I think place below the svg could also be used for an stats-toogle to show/hide climbing stats and comments if they are added later? I can create a pr if you want.

<img width="1135" alt="image" src="https://github.com/lemeryfertitta/Climbdex/assets/7480162/549031dc-e935-401c-8a99-ae5da713e757">

**Comment by lemeryfertitta** [comment]
Ah interesting, hadn't really thought of using the space below. Looks good in that image. Happy to accept a PR if you have one.

**Comment by gardaholm** [comment]
pr is done…
for now I would suggest hiding the divider if no description is shown, to keep the layout cleaner. 
if this section is also used for a stats toggle the divider may be shown by default …

**Comment by lemeryfertitta** [comment]
Thanks for the PR. Made a couple of changes and deployed.

I did notice that on the newer boards (e.g. TB2) a large percentage of the descriptions are just "No matching." Whereas on the original Kilter, the descriptions were a bit more inconsistent. I think this has to do with Aurora adding the no matching symbol during a later update after many of the most popular climbs had already been added to the older board's databases.

Anyways, I'm happy with the description display for now, but at some point it may be worth reconsidering the symbol-based approach instead of displaying the whole description. Also, if Climbdex was ever to host the data, I'd certainly prefer to just have a `matchingAllowed` boolean added to the climb data rather than hacking on a solution to the description like Aurora has done.

**Comment by gardaholm** [comment]
true – as TB2 owner I've mostly checked the TB2 descriptions so far ;) 
I tried some variations with the icon, and tried to add it when it matches the description on various spots, but somehow it always looked a bit off, and I'm with you to avoid cluttering the interface, otherwise it ends up looking like the app.
