### ISSUE TITLE
Classics (AKA benchmarks)

### ISSUE THREAD

**Issue by lemeryfertitta** [lemeryfertitta/Climbdex#39]
The Tension board has "Classics" which seems to be intended to be similar to the Moonboard "benchmark" feature. In the database, these climbs are distinguished by `climb_stats.benchmark_difficulty is not null`.

Interestingly, Kilter has not chosen to display Classics yet, though there are 112 climbs in the database that are marked with  a non-null benchmark_difficulty.

Some considerations:

- I'd like to avoid having too many filters, at least on the main filter screen. Perhaps some "additional filters" collapsible could be used to hide some filters. That being said, classics may be a more common filter. This could replace "difficulty accuracy" which was an experimental filter that I added.
- This would be exposing an "unreleased" feature for Kilter, which might be a bit confusing to users. On the other hand, this also might be a benefit of using Climbdex.
- Tension has an icon to indicate a climb is a classic. As mentioned in previous issues, it would be good to keep the interface clean, and I'm not sure how important this info is. Maybe the icon isn't needed and just a filter would suffice for now, or perhaps the description segment at the bottom could be used to also indicate classic status.

Interested to hear other opinions on this one, I have only used the "Classics" feature on the OG Tension board for a session or two. It was nice but didn't seem to have the level of importance that Moonboard benchmarks do.

**Comment by gardaholm** [comment]
I personally use the classics on the tension board a lot, i do them first and switch to "normal" climbs afterwards, I think such a filter is useful, at least on boards where classics are being used. 

Reducing filter options makes sense, because the interface is almost 100vh on my smartphone
- I also would recommend adding a "Advanced Filters" toggle
- I guess Min Ascents + Min Ratings are not really used and should therefor be moved into the advanced section.
- Grade Accuracy probably the same. I like the idea of it, but I'm not sure how accurate it is. My feeling is that a lot of people just quicklog their ascent and don't care about the grade. 
- A benchmark Icon in the filtered overview may be helpful (as are the tickmarks), but subtle as unicode char. I guess everybody familiar with these apps should recognize Ⓑ as benchmark or © as classic. 

<img width="366" alt="image" src="https://github.com/lemeryfertitta/Climbdex/assets/7480162/05907bb1-f7de-4e8e-8c56-87ef7ebc231a">

**Comment by lemeryfertitta** [comment]
> I guess Min Ascents + Min Ratings are not really used

I use min ascents with almost every filter, climbs with only 1 ascent are often pretty random. My favorite filters are to sort by rating descending with a decently large number of minimum ascents. That seems to work to find the best climbs of a grade. Also using hold finder with min ascents is great. I agree that min rating seems a little less useful and could move to additional filters.

So maybe for now, move rating + grade accuracy to advanced filters, which frees up one line of filters for a classics toggle.

Another idea for freeing up a line would be to combine min/max grades in a custom multi slider, [like this one](https://refreshless.com/nouislider/). I'll split that out to a separate issue.

> I guess everybody familiar with these apps should recognize Ⓑ as benchmark or © as classic.

I like the simplicity of the unicode character. Looks decent on that 2nd line in your picture - would the climb window show it as well? Because then it would probably need to be next to the difficulty/angle, and I'm not sure if I'd want it to be inconsistent.

**Comment by gardaholm** [comment]
> > I guess everybody familiar with these apps should recognize Ⓑ as benchmark or © as classic.
> 
> I like the simplicity of the unicode character. Looks decent on that 2nd line in your picture - would the climb window show it as well? Because then it would probably need to be next to the difficulty/angle, and I'm not sure if I'd want it to be inconsistent.

first I thought, no need to put it onto the climb window, but if you just swipe through the climb window, it would still be a nice information. then I would also move it next to the angle. Which probably makes sense, because the benchmarks are normally just for one certain grades. 

And i reduced the font size in the screenshit for the line with the ascent + rating information just slightly. I think this makes the difference between title and information a bit better.

**Comment by lemeryfertitta** [comment]
> I reduced the font size in the screenshot for the line with the ascent + rating information just slightly

I like it too, nice little improvement.

> I would also move it next to the angle.

Sounds good. So to summarize the changes for this one:

1. Add a new classics toggle to the filter screen. Maybe this should just be another `select` input even though a switch/checkbox is more appropriate, I remember playing with switches/checkboxes on this form and having a hard time getting it to look good. Maybe "Classics Only" would be the input name and "Yes"/"No" would be the options, with the default being "No."
2. Add © after the angle (and before the tick) in both the results list and climb display cards.
3. Reduce the size of the ascents and ratings text in the results list.

**Comment by lemeryfertitta** [comment]
This has been released. I have decided to include the "hidden" Kilter classics. I think this is a nice feature that Climbdex provides which is not yet provided by the official app.
