### ISSUE TITLE
Mirror Climbs

### ISSUE THREAD

**Issue by gardaholm** [lemeryfertitta/Climbdex#48]
In addition to the Bluetooth feature it would be great to also display the mirrored version of a climb (only if the board is set in mirrored layout), which will add another complexity in the navigation layout: see Issue #46 for UI suggestions

**Comment by ItsDang** [comment]
I'd like to work on this!

**Comment by lemeryfertitta** [comment]
Cool, thanks @ItsDang! @gardaholm has an in-flight PR that changes some of the UI on the results page so you will probably want to base off of that one until we get it merged. One easy UI solution for this would just be a "Mirror Climb" option in the dropdown menu that the in-progress PR is adding. Certainly open to other ideas though. Feel free to reach out if you have any questions or want any additional feedback!

**Comment by ItsDang** [comment]
Would you prefer it to be a mode like the current app? or a button that mirrors the climb?

**Comment by ItsDang** [comment]
For now I've set it as a toggle like the current apps.

**Comment by lemeryfertitta** [comment]
Deployed! Thanks @ItsDang

**Comment by ItsDang** [comment]
While testing the timestamp logging issue noticed that I couldn't log ascents on non mirrored layouts, was testing TB2 Spray. Due to a null on document.getElementById("button-mirror") and throwing Uncaught TypeError: Cannot read properties of null (reading 'classList'). I tested the fix on local. Will commit later today.
