### ISSUE TITLE
Log Timestamp

### ISSUE THREAD

**Issue by ItsDang** [lemeryfertitta/Climbdex#89]
With the addition of logging sends in #72, I noticed that everything is being set to the current UTC day at midnight. From my limited testing, it looks like the times showing in the official app stored/display in EDT/EST? What time does it show for other users? I switch the TZ around on my phone but the time displayed remained the same in the app.
If so send current Eastern time in log ascent.

**Comment by gardaholm** [comment]
I just added date for the logging in the first release, and didn't care about the time. 
But this can be added pretty easily …

**Comment by lemeryfertitta** [comment]
Thanks for the report and PR, merged in the fix. Will deploy with the mirror changes once those are in

**Comment by lemeryfertitta** [comment]
Deployed

**Comment by gardaholm** [comment]
@ItsDang did the Timestamp work for your timezone? 
I logged a route with climbdex today at 08:00 local time in Vienna (should be 06:00 GMT).
When I checked the entry in the aurora app I saw 01:00. So I think the timestamps are (still) off. 

When I check my Logbook export (or in the aurora app) the timestamps are shown in my local timezone, at least it looks like, because I did the boulders in the evening.
<img width="430" alt="image" src="https://github.com/user-attachments/assets/42fb2ce8-fa51-4a58-8650-9a6b4ea9c346">

but didnt spent much time checking this, just realized it when I controlled the tick of the mirrored route today …

**Comment by ItsDang** [comment]
@gardaholm Hmm, yeah it "works" for me because it's set to EST, { timeZone: 'America/New_York'}, I think this needs to be removed and it should work for you too. Since the timezone isn't being stored, just storing local time seems best. I'll commit the change later today.

**Comment by lemeryfertitta** [comment]
Fix should be deployed
